dist: trusty
sudo: required
compiler: clang
language: cpp
env:
  global:
  - secure: S0pRfjbIwhvz5WDm0Lwdn8qi7JNCwR6HfWqYflhA/5lNBlYNgJ32AKTvIKeVK6tKGog3wJTG5tKDM+LZFYNYyGI1HnZm+ybfNKcCztwmj8FiHWlio7WMhkD+vYCSrnKL+dKWkcNg/22hjODbGNKNY7LfU4F5+x9zDA8HDJW3zNPzgJWX21b0my7RN25UHR0+YNgPJ5XKp9zlhlabDA6e/PlZ2k08GqTYTywOo892rrLQg7nZQ3WqZCTqIkQF8sgkJTI2Po2+Xefi9akrK1CHe+TdhAoff3DmVb4UZLguqF6r7nw0Wbpy+hlf3rxLWjCYWZQOo+F97VFotz6GMhQbLR7a4+z9ZLYutzlNQeWik2f12kfq4P9huVWlifsPI5XdE836Uj6yYcmeKdfnnt8QNivpwgqZKYEc+IqDavqKq6XhvB/qEXcuTjGdUxFhKPaNEqszDyNaf2vCV6SV2r0I1aVZXjRLRpLb2TFoQdbVZCJVyYMTQeRdPLtG46iI1bk7Yn9qsKXS/lvm7fA3gzxCEQvKBBrmsd+G8koxXEvPyMAJvhjYVfdP1m3G982TkjOfbcGQ0DFBSXcy0zQ1H2tKtjKa7wXGBDZxNX3lqihzqz+e547PutjepU3cDIwqqadyNyf65AMz6QaV8us2IxTToBxeJPYjTkybqBJZ83N7uKo=
install: sudo apt install -q lcov libnotify-dev
script: make && make tests
after_success:
- |2

  declare -r SSH_FILE="$(mktemp -u $HOME/.ssh/XXXXX)"

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  # Decrypt the file containing the private key
  # (Note: this is the same as what is generated by the Travis CLI at step 2.5)

  openssl aes-256-cbc \
    -K $encrypted_XXXXXXXXXXXX_key \
    -iv $encrypted_XXXXXXXXXXXX_iv \
    -in ".travis/github_deploy_key.enc" \
    -out "$SSH_FILE" -d

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  # Enable SSH authentication

  chmod 600 "$SSH_FILE" \
    && printf "%s\n" \
         "Host github.com" \
         "  IdentityFile $SSH_FILE" \
         "  LogLevel ERROR" >> ~/.ssh/config

- make package

deploy:
  provider: releases
  api_key:
    secure: d5CYE+u9oB3luTC4X7uM2PfCyYwwRMmZABDsDjyB3/7W5deEHVHvU4j3Ud+fdV7W6iRkgrTJU2gT0yy8daPO1rb28f7we7gqb6hE8+tNYniu8NDEPIj5EQuK2VVJJBCPcm/zrkiyIMi5rz3dIM9E54csItIxJi6B2PgqNWxPpPzjha9FNVBGNSkbIYzXzw7tP6sL1VPMJmFR+GZqGjnxV+UTK6r+BR6ZO7bY+VmrCncUO1f3njgEEQeJqj077B5ci2G44iT0n3PngUuds2epironOCbQJCIjhSocr3O55v+ToVtuzaDgbEyfRSBrMz1nEn6YCxrtnhoy3VlHoGkoJZ8LzRx2Bu1Z/rz9w3BXFtW/NoLkTs0NbXS5JwjJeeMFBgbF2UV+juzeN6WdtpCMnytEB7VqrZol6uJM8TkHVFmibc0t2KWhYrtEig7nr5H2d5a/s2iFL4/VZWn+h9of61gmsrdXQsxOaB67r4IridiTHkZilDSdqpGoEAgupaa0eEakZb4MMgNQKRxZ4bBJyoFiL7h2rLIbuMqNyNrDP7ISCNEwDn7nDyul8+AtCsmJ5M5BD5DZSFgrHLEJBqnKnMCEFbIwGH6majB0Ugt47vsnIhLRyhDiZqhKgvlskkWqmDf4ymCs9EVlLyfVBb8QPKRUz4Sd6o/eMa6+iZ0IQvc=
  file: libnotify-terminal.tar.gz
  skip_cleanup: true
  on:
    tags: true
